version: 2

project_name: gh-mfmatt

before:
  hooks:
    - go mod download

builds:
  - main: .
    binary: gh-mfmatt
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  mode: keep-existing
