name: Release

on:
  push:
    branches: [main]

jobs:
  release-please:
    uses: matt-riley/matt-riley-ci/.github/workflows/release-please.yml@4ff76b1a606b1fbba163119a65bf7b05f91ab9b6 # v3
    secrets: inherit

  goreleaser:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    uses: matt-riley/matt-riley-ci/.github/workflows/go-goreleaser.yml@4ff76b1a606b1fbba163119a65bf7b05f91ab9b6 # v3
    secrets: inherit
